### ISSUE TITLE
trouble building - make failure in dbus-analyze-types.py

### ISSUE THREAD

**Issue by rburcham** [tieto/pidgin#1]
In the effort to build and study the mods that enable screen sharing in sipe & pidgin, I have pulled down farstream, libnice, pidgin and sipe from /tieto, and I am trying to build everything on my Gentoo laptop and install to /usr/local/

I have built farstream and libnice, and I am now working on building pidgin.  I've run the autogen.sh  and prepared a my-configure.sh script that looks like this:

    #!/bin/bash
    
    FARSTREAM_CFLAGS="-I/usr/local/include/farstream-0.2"
    FARSTREAM_LIBS="-L/usr/local/lib/farstream-0.2 -Wl,rpath -Wl,/usr/local/lib/farstream-0.2"
    
    GSTREAMER_CFLAGS="-I/usr/local/include -I/usr/local/include/nice -I/usr/local/include/stun"
    GSTREAMER_LIBS="-L/usr/local/lib -Wl,rpath -Wl,/usr/local/lib -L/usr/local/lib/gstreamer-1.0 -Wl,rpath -Wl,/usr/local/lib/gstreamer-1.0 -L/usr/local/lib/gstreamer-0.10 -Wl,rpath -Wl,/usr/local/lib/gstreamer-0.10"
    
    GPLUGIN_CFLAGS="-I/usr/include/gplugin-1.0 -I/usr/include/gplugin-1.0/gplugin -I/usr/include/gplugin-1.0/gplugin-gtk"
    GPLUGIN_LIBS="-L/usr/lib64 -Wl,rpath -Wl,/usr/li64 -L/usr/lib64/gplugin -Wl,rpath -Wl,/usr/lib64/gplugin"
    
    ./configure --prefix=/usr/local --disable-avahi --with-dbus-services=/usr/share/dbus-1/services

After running this I go to `make` and it fails with:

    # make
    make  all-recursive
    make[1]: Entering directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad'
    Making all in .
    make[2]: Entering directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad'
      GEN      package_revision_raw.txt
      GEN      package_revision.h
    make[2]: Leaving directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad'
    Making all in m4macros
    make[2]: Entering directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad/m4macros'
    make[2]: Nothing to be done for 'all'.
    make[2]: Leaving directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad/m4macros'
    Making all in libpurple
    make[2]: Entering directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad/libpurple'
      GEN      enums.h
      GEN      marshallers.h
      GEN      enums.c
      GEN      marshallers.c
      GEN      dbus-bindings.c
      GEN      dbus-signals.c
      GEN      dbus-types.c
    Traceback (most recent call last):
      File "./dbus-analyze-types.py", line 50, in <module>
        for line in myinput:
      File "/usr/lib64/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3519: ordinal not in range(128)
    Makefile:1766: recipe for target 'dbus-types.c' failed
    make[2]: *** [dbus-types.c] Error 1
    make[2]: Leaving directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad/libpurple'
    Makefile:673: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/usr/src/pidgin-sipe-alpha/pidgin-launchpad'
    Makefile:587: recipe for target 'all' failed
    make: *** [all] Error 2

The generated dbus-types.c is incomplete with the last entry

    PURPLE_DBUS_DEFINE_TYPE(PurpleNotifySearchButton)

If I try to make again and again and again it'll will skip/stumble past the broken entries and continue, but then obviously at compile time there are missing defines and things break.

What do I do to properly fix this?

**Comment by rburcham** [comment]
Worked around this with
`# PYTHONIOENCODING='utf-8' make`
